### ISSUE TITLE
Add search by IP address

### ISSUE THREAD

**Issue by luigisiricola1997** [beliven-it/hssh#10]
It would be nice If I can be able to search for a host also through its IP.

**Comment by CasvalDOT** [comment]
The request is currently in progress

**Comment by CasvalDOT** [comment]
@valentinocossar I've include in the develop branch the search through IP. The implementation is very simple
Instead search through a list of host names, now the list appear like this:
```
hostname -> 1.2.3.4
```

This take full advantage of searching using fuzzy search engine. 
For now I have not provided a flag to enable the appearance of the IP but it appear as default.

**Comment by valentinocossar** [comment]
@CasvalDOT thank you! I'll test it as soon as possible. Anyway, I don't think that a flag to "disable" the IP from the list is really needed.
