### ISSUE TITLE
Add missing description

### ISSUE THREAD

**Issue by CasvalDOT** [beliven-it/hssh#12]
The description aside is missing.
![screenshot_1615933481](https://user-images.githubusercontent.com/8190931/111388134-b1c36d80-86a6-11eb-8b73-3bc89323723c.png)

**Comment by valentinocossar** [comment]
@CasvalDOT description added.

![image](https://user-images.githubusercontent.com/4087384/111388295-4e8a0900-86af-11eb-9c3e-f60064610a46.png)
