### ISSUE TITLE
Status of connection

### ISSUE THREAD

**Issue by CasvalDOT** [beliven-it/hssh#13]
Can you make sense to set up a flag to apply a control over the connection status? I have a lot of hosts I don't have access, it would be nice to know what I can connect and to what not, what do you think?

An example could be:
```
hssh l --status-ok
```
The functions for each host perform a test connection and print the only available host.

**Comment by valentinocossar** [comment]
Mmm, idk! What happens if you try to connect outside of a VPN? You have a non-realistic result. I'm not sure about this implementation. Keep in mind that with the new JumpCloud provider we can sync only user-related hosts.
