### ISSUE TITLE
Daemon for automatic sync

### ISSUE THREAD

**Issue by CasvalDOT** [beliven-it/hssh#14]
It may also be useful to set up a command / flag that launches the background application and dealing with the sync of the data remotely.

```bash
hssh -d
```
or
```
hsshd
```

**Comment by valentinocossar** [comment]
This makes sense, but it's worth implementing it as a [Homebrew service](https://github.com/Homebrew/homebrew-services) instead of an independent daemon.

**Comment by CasvalDOT** [comment]
Please look issue #28 for a different approach
