### ISSUE TITLE
Integrate unit tests

### ISSUE THREAD

**Issue by CasvalDOT** [beliven-it/hssh#17]
I've start adding some unit test, More test must be done!!

**Comment by valentinocossar** [comment]
![bugs](https://user-images.githubusercontent.com/4087384/111889247-13a41000-89e4-11eb-9d93-82024183c8f4.gif)

**Comment by CasvalDOT** [comment]
Add an action to perform the implemented test, on push and pull request

**Comment by valentinocossar** [comment]
So we can close this issue? Have you already tested it? 😉

**Comment by CasvalDOT** [comment]
No yet! I would create more test

**Comment by valentinocossar** [comment]
Closed by #21
