### ISSUE TITLE
Remove the connection argument?

### ISSUE THREAD

**Issue by luigisiricola1997** [beliven-it/hssh#18]
It would be easier if I could connect throught SSH without specify the command argument.
ie: `hssh hostname`

**Comment by valentinocossar** [comment]
@luigisiricola1997 this functionality is already provided by the `ssh` command. And could create conflicts between hostnames and `hssh` commands. Right now it's required a lot of effort to implement the same functionality provided by `ssh` and the fact is that would be a bare clone.
