### ISSUE TITLE
Using Host with multiple alias hssh is unable to connect

### ISSUE THREAD

**Issue by paolovisintin** [beliven-it/hssh#38]
Hello!, 
when my ssh config has multiple aliases in Host declaration, hssh fails to connect, 
this is an example: 

```Host cloudtik-webpanel-prod cloudtik-prod
    Hostname 1.2.3.4
    Port 22
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    User root
    IdentityFile ~/.ssh/id_rsa

**Comment by CasvalDOT** [comment]
Hi! Probabily the alias doesn't work because the alias name use whitespaces. I'll check if this is the reason for this issue!

**Comment by CasvalDOT** [comment]
Ok! I must confirm that the issue is related to whitespaces inside alias name.
For example:

```bash
Host test- lab-personal
  Hostname 1.2.3.4
  User root
  ...
```

When you select this host using `hssh c` an error occured.

```bash
bash: lab-personal: command not found
```

**Comment by CasvalDOT** [comment]
I've made some tests using normal SSH command:

First: leaving the host attribute without quotes:

```bash
Host test- lab-personal
  Hostname ...
...

ssh "test- lab-personal"

# The output is:
ssh: Could not resolve hostname test- lab-personal: Name or service not known
```

Using the host attribute with quotes:

```bash
Host "test- lab-personal"
  Hostname ...
...

ssh "test- lab-personal"

# It works!!!
```

Using `hssh c` in the list you will see the entry surrounded by quotes:

```bash
> "test- lab-personal" -> 1.2.3.4
```

Selecting this entry you are now able to connect.

**Comment by beliven-fabrizio-gortani** [comment]
Ok, I've now understand the problem. HSSH should try to duplicate the host configuration in the list in this way:
```bash
# For example
Host test test2 test3
    Hostname 1.2.3.4
    Port 22
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
    User root
    IdentityFile ~/.ssh/id_rsa
```
the host list should print three entries like:

```bash
test -> 1.2.3.4
test2 -> 1.2.3.4
test3 -> 1.2.3.4
```
Now I'll try to understand how to implement this behavior

**Comment by beliven-fabrizio-gortani** [comment]
@paolovisintin  I've created a Draft pull request for this feature #39. After finish some checks and tests I'll merge in master branch and create a new release.
