### ISSUE TITLE
Add example config file in README

### ISSUE THREAD

**Issue by valentinocossar** [beliven-it/hssh#6]
Add example config file in README to allow simple copy/paste if someone doesn't want to rely on the config file auto-creation feature.

**Comment by CasvalDOT** [comment]
Maybe an animated GIF or [asciinema recorded session](https://asciinema.org/) can be useful.
We can also improve the aesthetic of the README adding a banner image on top of the page.

**Comment by valentinocossar** [comment]
Sure, but I don't think a video on how to configure the file is the best approach to solve this. Certainly, we can use asciinema recorded session to better explain the CLI usage.
